name: python_course_dev
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - dcm2niix
  - distro
  - anaconda::ipykernel
  - ipython
  - ipympl
  - jupyterlab
  - matplotlib
  - nibabel
  - nilearn
  - numpy
  - pandas
  - Pillow
  - regex
  - scikit-image
  - scikit-learn
  - seaborn
  - stardist
  - statsmodels
  - tensorflow
  - widgetsnbextension
  - pip:
    - opencv-python
    - tensorflow-io-gcs-filesystem
